### ISSUE TITLE
TKK generated

### ISSUE THREAD

**Issue by extensionsapp** [k3rn31p4nic/google-translate-api#7]
Hey.

Did you manage to figure out how TKK is generated?

`var code = res.body.match(/TKK='.*?';/g);`

**TKK=** not found in HTML `https://translate.google.com`

![tkk](https://user-images.githubusercontent.com/8192379/61499949-aef40f00-a9d1-11e9-9bdb-948426f8d31a.png)

Where does TKK come from?

Maybe this: `tkk:'434303.3040823967'`

**Comment by k3rn31p4nic** [comment]
> TKK= not found in HTML https://translate.google.com

Even if the regex is not able to find it, it doesn't actually matter because:
https://github.com/k3rn31p4nic/google-translate-api/blob/411112851b27c6bd5698f6344a65f367e5dbc87a/src/tokenGenerator.js#L92-L93


> Where does TKK come from?
> Did you manage to figure out how TKK is generated?

TKK is a global variable that's used as a seed by the token generator to generate the token. And as it's a global variable available across the page, either there might be some other script that generates it or it's being generated server side. So, currently, TKK is being scraped from their site.

**Comment by ZuBB** [comment]
seems this is being cared in https://github.com/k3rn31p4nic/google-translate-api/pull/10
